### ISSUE TITLE
Video Re-ID Dataset-Labeled Pedestrian in the Wild

### ISSUE THREAD

**Issue by ghost** [NEU-Gou/awesome-reid-dataset#1]
Labeled Pedestrian in the Wild
[Dataset Link](http://liuyu.us/dataset/lpw/index.html)

**Comment by gceboh** [comment]
@NEU-Gou 
Thanks. It seems the image example of LPW in `readme.md` doesn't exist.
https://github.com/NEU-Gou/awesome-reid-dataset/blob/master/imgs/eg_lpw.png

Also,
https://github.com/NEU-Gou/awesome-reid-dataset/blob/master/imgs/eg_pkusketch.png
https://github.com/NEU-Gou/awesome-reid-dataset/blob/master/imgs/eg_thermalworld.jpg
