### ISSUE TITLE
The url of MARS dataset is not available

### ISSUE THREAD

**Issue by AnselDai** [NEU-Gou/awesome-reid-dataset#4]
When I clicked the link of MARS dataset, it turned to a 404 page. Can the author update the url of MARS dataset? I have not found it yet.

**Comment by ye12121** [comment]
Well, MSMT17 has the same problem.

**Comment by NEU-Gou** [comment]
@AnselDai @ye12121 
I double checked the link through the author's webpage. Seems that both MARS and MSMT17 are not accessible now. Have no idea what happens there...
