### ISSUE TITLE
questions from a rookie

### ISSUE THREAD

**Issue by goldentimecoolk** [NEU-Gou/awesome-reid-dataset#9]
Hi, I'm new to reid. Your dataset list is very useful. But I have one simple question.
What does it mean in the last two columns, tracking sequences and full frames availability? In addition, does multi-shot mean that there are more than one images used to query? Thank you!

**Comment by NEU-Gou** [comment]
- Tracking sequences meaning whether the images of the same ID in one camera are from consecutive video frames.  
- Full frames available meaning the original full size frames are also released. 
- Multi-shot here simply meaning there are more than one images for each ID.
